# Generated by Django 3.2.3 on 2023-08-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230803_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hexcolor',
            new_name='color',
        ),
    ]
