# Generated by Django 3.2.3 on 2023-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230805_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='IngredientAmount',
        ),
    ]
